// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ_VQLWV0f7Zl8d4wKjiWBC6LsF4sVPYY',
    appId: '1:747875914385:web:d5f0ec89ad8adfe5522530',
    messagingSenderId: '747875914385',
    projectId: 'brewlogapp',
    authDomain: 'brewlogapp.firebaseapp.com',
    storageBucket: 'brewlogapp.firebasestorage.app',
    measurementId: 'G-RX3HEZT4D7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd4646xT20Oa9IXIHzVYNx0pSNPVc6rP8',
    appId: '1:747875914385:android:f4fc80650a53b15e522530',
    messagingSenderId: '747875914385',
    projectId: 'brewlogapp',
    storageBucket: 'brewlogapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH-mnnZa_l8Hl92ZZJLGe3P1WRP6mk_jI',
    appId: '1:747875914385:ios:35c48865a64eead0522530',
    messagingSenderId: '747875914385',
    projectId: 'brewlogapp',
    storageBucket: 'brewlogapp.firebasestorage.app',
    iosBundleId: 'com.example.brewLog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH-mnnZa_l8Hl92ZZJLGe3P1WRP6mk_jI',
    appId: '1:747875914385:ios:35c48865a64eead0522530',
    messagingSenderId: '747875914385',
    projectId: 'brewlogapp',
    storageBucket: 'brewlogapp.firebasestorage.app',
    iosBundleId: 'com.example.brewLog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJ_VQLWV0f7Zl8d4wKjiWBC6LsF4sVPYY',
    appId: '1:747875914385:web:cdb63a0788659b82522530',
    messagingSenderId: '747875914385',
    projectId: 'brewlogapp',
    authDomain: 'brewlogapp.firebaseapp.com',
    storageBucket: 'brewlogapp.firebasestorage.app',
    measurementId: 'G-JQXFCDH1DB',
  );
}
